project_id = "yxdcewlkigvqfnyxywag"

[functions.validate-okx-apikey]
verify_jwt = false

[functions.withdraw-okx]
verify_jwt = false

[functions.validate-binance-apikey]
verify_jwt = false

[functions.withdraw-binance]
verify_jwt = false
